spring:
  application:
    name: rasberry_api_management

telegram:
  bot:
    token: ${telegramToken}
    username: ${botUserName}

config:
  rclone:
    enable: ${rcloneEnable}
    profile: ${rcloneProfile}
    pathBackupFolder: ${pathBackupFolder}
    saveTokenInApp: ${saveTokenInApp}
    pathRcloneConfig: ${pathRcloneConfig}
    rcloneCron: ${rcloneCron}
    idChannelTelegram: ${idChannel}